title: The Third Bit
subtitle: Start where you are, use what you have, help who you can.
url: https://third-bit.com
repository: gvwilson/thirdbit

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - '.#*'
  - '*~'

permalink: pretty
paginate: 10
paginate_path: /blog/:num

author:
  name: Greg Wilson
  url: third-bit.com
  email: gvwilson@third-bit.com
  calendly: https://calendly.com/gvwilson
  github: https://github.com/gvwilson
  mastodon: https://mastodon.social/@gvwilson
  linkedin: https://www.linkedin.com/in/greg-wilson-a26510b6/
  youtube: https://www.youtube.com/channel/UCbDQ7FIeYB3FHRADAjUjfrg

links:
  browsercast: https://gvwilson.github.io/browsercast/
  dragnet: https://gvwilson.github.io/dragnet/

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
