title: The Third Bit
subtitle: Start where you are, use what you have, help who you can.
url: https://third-bit.com
repository: gvwilson/thirdbit

markdown: kramdown
highlighter: rouge

exclude:
  - '*.sublime-*'
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor/bundle
  - '.#*'

permalink: pretty
paginate: 10
paginate_path: /blog/:num

author:
  name: Greg Wilson
  url: third-bit.com
  email: gvwilson@third-bit.com
  calendly: https://calendly.com/gvwilson
  github: https://github.com/gvwilson
  mastodon: https://mastodon.social/@gvwilson
  linkedin: https://www.linkedin.com/in/greg-wilson-a26510b6/
  youtube: https://www.youtube.com/channel/UCbDQ7FIeYB3FHRADAjUjfrg

links:
  dragnet: https://gvwilson.github.io/dragnet/

papers:
  - author: "Wilson"
    title: "Twelve quick tips for software design"
    url: "https://doi.org/10.1371/journal.pcbi.1009809"
    year: 2022
  - author: "Smalls & Wilson"
    title: "Ten quick tips for staying safe online"
    url: "https://doi.org/10.1371/journal.pcbi.1008563"
    year: 2021
  - author: "Lin et al"
    title: "Ten quick tips for making things findable"
    url: "https://doi.org/10.1371/journal.pcbi.1008469"
    year: 2020
  - author: "Nederbragt et al"
    title: "Ten quick tips for teaching with participatory live coding"
    url: "https://doi.org/10.1371/journal.pcbi.1008090"
    year: 2020
  - author: "Denny et al"
    title: "Research this! Questions that computing educators most want computing education researchers to answer"
    url: "https://dl.acm.org/doi/abs/10.1145/3291279.3339402"
    year: 2019
  - author: "Sholler et al"
    title: "Ten simple rules for helping newcomers become contributors to open projects"
    url: "https://doi.org/10.1371/journal.pcbi.1007296"
    year: 2019
  - author: "Wilson"
    title: "Ten quick tips for creating an effective lesson"
    url: "https://doi.org/10.1371/journal.pcbi.1006915"
    year: 2019
  - author: "Brown & Wilson"
    title: "Ten quick tips for teaching programming"
    url: "https://doi.org/10.1371/journal.pcbi.1006023"
    year: 2019

years:
  - low: 2020
    high: 2029
    start: 2020
    end: 2023
  - low: 2010
    high: 2019
    start: 2010
    end: 2019
  - low: 2000
    high: 2009
    start: 2004
    end: 2009

plugins:
  - jekyll-paginate
  - jekyll-sitemap
